
package UseView;

import com.raven.datechooser.SelectedDate;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

public class Spa extends javax.swing.JFrame {

   
    public Spa() {
        initComponents();
        setLocationRelativeTo(null);
        
        String rutaImagen = "./img/spa1.jpg";

        ImageIcon icono = new ImageIcon(getClass().getClassLoader().getResource(rutaImagen));
        int anchoLabel = HClabelimg.getWidth();
        int altoLabel = HClabelimg.getHeight();

        Image imagen = icono.getImage();

        Image imagenAjustada = imagen.getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);

        ImageIcon iconoAjustado = new ImageIcon(imagenAjustada);

        HClabelimg.setIcon(iconoAjustado);
        
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        SaveButton.setUI(new RoundedButtonUI(new Color(100, 180, 255), Color.BLACK));
        SaveButton.setBounds(50, 50, 200, 50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        HClabelimg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ownerNametxt = new javax.swing.JTextField();
        idOwner = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        petNamejtf = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        PanelCita = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        am10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        am11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        am12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        am1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        FechayHoratxt = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(381, 1587));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(HClabelimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 13, 335, 279));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Add personal details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 353, 175, -1));

        ownerNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerNametxtActionPerformed(evt);
            }
        });
        jPanel1.add(ownerNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 380, 350, 31));
        jPanel1.add(idOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 451, 350, 31));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 424, 350, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add pet details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pet name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 538, 67, -1));

        petNamejtf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        petNamejtf.setForeground(new java.awt.Color(153, 153, 153));
        petNamejtf.setText("name");
        petNamejtf.setToolTipText("");
        petNamejtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                petNamejtfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                petNamejtfFocusLost(evt);
            }
        });
        petNamejtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNamejtfActionPerformed(evt);
            }
        });
        jPanel1.add(petNamejtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 565, 350, 31));

        SaveButton.setText("Save");
        jPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 700, -1, -1));

        PanelCita.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Time");

        dateChooser1.setForeground(new java.awt.Color(204, 0, 255));
        dateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateChooser1MouseClicked(evt);
            }
        });

        am10.setPreferredSize(new java.awt.Dimension(78, 0));
        am10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                am10MouseDragged(evt);
            }
        });
        am10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                am10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                am10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                am10MouseExited(evt);
            }
        });
        am10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("10:00 AM");
        am10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        am11.setPreferredSize(new java.awt.Dimension(78, 22));
        am11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                am11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                am11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                am11MouseExited(evt);
            }
        });
        am11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("11:00 AM");
        am11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        am12.setPreferredSize(new java.awt.Dimension(78, 22));
        am12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                am12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                am12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                am12MouseExited(evt);
            }
        });
        am12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("12:00 AM");
        am12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        am1.setPreferredSize(new java.awt.Dimension(78, 0));
        am1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                am1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                am1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                am1MouseExited(evt);
            }
        });
        am1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("01:00 PM");
        am1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 30));

        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        FechayHoratxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FechayHoratxt.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout PanelCitaLayout = new javax.swing.GroupLayout(PanelCita);
        PanelCita.setLayout(PanelCitaLayout);
        PanelCitaLayout.setHorizontalGroup(
            PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitaLayout.createSequentialGroup()
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(am1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCitaLayout.createSequentialGroup()
                                    .addComponent(am10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(am11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(am12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(FechayHoratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCitaLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(ConfirmButton)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        PanelCitaLayout.setVerticalGroup(
            PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(am11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(am12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(am10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addComponent(am1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(FechayHoratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmButton)
                .addContainerGap())
        );

        jPanel1.add(PanelCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Servicio de Spa Cocker desde $50.000", "- Servicio de Spa Dachshund $40.000", "- Servicio de Spa French Poodle $50.000", "- Servicio de Spa Husky $70.000", "- Servicio de Spa Pastor Alemán $70.000", "- Servicio de Spa Pinsher $40.000", "- Servicio de Spa Pug $40.000", "- Servicio de Spa Schnauzer $50.000", "- Servicio de Spa Shit-Zu $50.000", "- Servicio de Spa Yorkshire $40.000", "- Servicio de Spa Beagle $40.000", "- Servicio de Spa Golden Retriever $70.000", "- Servicio de Spa Mestizos Raza Unica $40.000", "- Servicio de Spa Labrador $60.000", "- Servicio de Spa Pamerania $40.000", "- Servicio de Spa Bulldog F $40.000" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 330, 30));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void petNamejtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNamejtfActionPerformed

    }//GEN-LAST:event_petNamejtfActionPerformed

    private void petNamejtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petNamejtfFocusLost
        if (petNamejtf.getText().equals(""))
        {
            petNamejtf.setText("name");
            petNamejtf.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_petNamejtfFocusLost

    private void petNamejtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_petNamejtfFocusGained
        if (petNamejtf.getText().equals("name"))
        {
            petNamejtf.setText("");
            petNamejtf.setForeground(new Color(0, 0, 0));
        };
    }//GEN-LAST:event_petNamejtfFocusGained

    private void ownerNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerNametxtActionPerformed

    private void dateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooser1MouseClicked

    }//GEN-LAST:event_dateChooser1MouseClicked

    private void am10MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am10MouseDragged

    }//GEN-LAST:event_am10MouseDragged

    private void am10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am10MouseClicked
        SelectedDate D = dateChooser1.getSelectedDate();
        System.out.println(D.getDay()+"/"+D.getMonth()+"/"+D.getYear());
        FechayHoratxt.setText("<html>"+ "Fecha:  "+D.getDay()+"/"+D.getMonth()+"/"+D.getYear() + "<br>" +"Hora:  10:00 AM" + "</html>");
    }//GEN-LAST:event_am10MouseClicked

    private void am10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am10MouseEntered

        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_am10MouseEntered

    private void am10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am10MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_am10MouseExited

    private void am11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am11MouseClicked
        SelectedDate D = dateChooser1.getSelectedDate();
        System.out.println(D.getDay()+"/"+D.getMonth()+"/"+D.getYear());
        FechayHoratxt.setText("<html>"+ "Fecha:  "+D.getDay()+"/"+D.getMonth()+"/"+D.getYear() + "<br>" +"Hora:  11:00 AM" + "</html>");
    }//GEN-LAST:event_am11MouseClicked

    private void am11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am11MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_am11MouseEntered

    private void am11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am11MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_am11MouseExited

    private void am12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am12MouseClicked
        SelectedDate D = dateChooser1.getSelectedDate();
        System.out.println(D.getDay()+"/"+D.getMonth()+"/"+D.getYear());
        FechayHoratxt.setText("<html>"+ "Fecha:  "+D.getDay()+"/"+D.getMonth()+"/"+D.getYear() + "<br>" +"Hora:  12:00 AM" + "</html>");
    }//GEN-LAST:event_am12MouseClicked

    private void am12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am12MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_am12MouseEntered

    private void am12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am12MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_am12MouseExited

    private void am1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am1MouseClicked
        SelectedDate D = dateChooser1.getSelectedDate();
        System.out.println(D.getDay()+"/"+D.getMonth()+"/"+D.getYear());
        FechayHoratxt.setText("<html>"+ "Fecha:  "+D.getDay()+"/"+D.getMonth()+"/"+D.getYear() + "<br>" +"Hora:  01:00 PM" + "</html>");
    }//GEN-LAST:event_am1MouseClicked

    private void am1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am1MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_am1MouseEntered

    private void am1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am1MouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_am1MouseExited

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed

    }//GEN-LAST:event_ConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spa().setVisible(true);
            }
        });
    }

    public JLabel getHClabelimg() {
        return HClabelimg;
    }

    public void setHClabelimg(JLabel HClabelimg) {
        this.HClabelimg = HClabelimg;
    }

    public JTextField getIdOwner() {
        return idOwner;
    }

    public void setIdOwner(JTextField idOwner) {
        this.idOwner = idOwner;
    }

    public JButton getSaveButton() {
        return SaveButton;
    }

    public void setSaveButton(JButton SaveButton) {
        this.SaveButton = SaveButton;
    }

    

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextField getOwnerNametxt() {
        return ownerNametxt;
    }

    public void setOwnerNametxt(JTextField ownerNametxt) {
        this.ownerNametxt = ownerNametxt;
    }

    public JTextField getPetNamejtf() {
        return petNamejtf;
    }

    public void setPetNamejtf(JTextField petNamejtf) {
        this.petNamejtf = petNamejtf;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel FechayHoratxt;
    private javax.swing.JLabel HClabelimg;
    private javax.swing.JPanel PanelCita;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel am1;
    private javax.swing.JPanel am10;
    private javax.swing.JPanel am11;
    private javax.swing.JPanel am12;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JTextField idOwner;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ownerNametxt;
    private javax.swing.JTextField petNamejtf;
    // End of variables declaration//GEN-END:variables
}
